db:
  migrate_dir: "migrates"
  dsn: "postgres://nikolay:12345@localhost:5434/docs_database?sslmode=disable"
docs_store:
  secure: false
  endpoint: minio-docs_server
  access_key: "nikolay"
  secret_key: "12345"
loglevel: -4